### PR TITLE
Implemented Editing Institutions

### PR DESCRIPTION
**Pull request by spapaseit**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@spapaseit Looks great! Any reason why you'd include the Debug config files inside the projects?
@marijngiesen Will put it on the staging machine

**Comment by spapaseit** [comment]
@ErikSchierboom I'm using Visual Studio 2015, which has a watch on the solution folder and tends to add any files you drop into that folder automatically to the solution. Sorry about that. 
I've removed the Debug config files already and will push again to this branch.

Do you want me to make another PR for this change?

**Comment by ErikSchierboom** [comment]
@spapaseit Nope, if you could push the updated version, @marijngiesen will put it on our staging environment

**Comment by spapaseit** [comment]
@ErikSchierboom, @marijngiesen, Done!

**Comment by marijngiesen** [comment]
@spapaseit Great work, thanks!

**Pull request merged**
