### PR TITLE
Bulk import

### PR DESCRIPTION
**Pull request by spapaseit**
This branch implements the ability to import Journal Licenses in bulk from an Excel file. 

Examples of correct and incorrect import files are included in Core.Tests\Import\Licenses\Stubs.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@spapaseit Could you do a rebase to squash related commits (e.g. to combine all similar case numbers into single commits)?

**Comment by spapaseit** [comment]
@ErikSchierboom Done... as far as I could. Any commits before pulling your directory restructuring result in merge conflicts when rebasing. Hope this little bit helps though.

**Comment by ErikSchierboom** [comment]
@spapaseit I think I will be restructuring the files later, probably tomorrow.

**Comment by ErikSchierboom** [comment]
@spapaseit You had a bit of bad luck as my restructuring indeed made it extremely hard to merge. That is why I did a manual merge. The end result can be found in the `bulk-import-fixed` branch: https://github.com/QOAM/qoam/tree/bulk-import-fixed My suggestion is that you use the files in this branch to send a new PR based on the latest master, that should fix things.

And I also suggest that you check if my manual merge did not break anything. Sorry for the hassle.

**Comment by spapaseit** [comment]
@ErikSchierboom No problem. Will do!

**Comment by spapaseit** [comment]
@ErikSchierboom Everything looks good. I'll do a new PR on the new branch

**Pull request closed without merging**
